# This rule is not used by the project krun itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the blocks.krun.io.
# This role is intended for users who need to fully manage ansibleblocks resources,
# including managing their lifecycle, but without administrative access to all cluster resources.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: krun
    app.kubernetes.io/managed-by: kustomize
  name: ansibleblock-editor-role
rules:
- apiGroups:
  - blocks.krun.io
  resources:
  - ansibleblocks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - blocks.krun.io
  resources:
  - ansibleblocks/status
  verbs:
  - get
