---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for tasks.krun.io/v1alpha1, Kind: AnsibleTask
  ##
  - apiGroups:
      - tasks.krun.io
    resources:
      - ansibletasks
      - ansibletasks/status
      - ansibletasks/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for roles.krun.io/v1alpha1, Kind: AnsibleRole
  ##
  - apiGroups:
      - roles.krun.io
    resources:
      - ansibleroles
      - ansibleroles/status
      - ansibleroles/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for blocks.krun.io/v1alpha1, Kind: AnsibleBlock
  ##
  - apiGroups:
      - blocks.krun.io
    resources:
      - ansibleblocks
      - ansibleblocks/status
      - ansibleblocks/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
# +kubebuilder:scaffold:rules
