apiVersion: tasks.krun.io/v1alpha1
kind: AnsibleTask
metadata:
  name: ansibletask-example-02-conditions
spec:
  action: ansible.builtin.debug
  args:
    msg: "Conditional task example"
  when: "true"
  changedWhen: "false"
  failedWhen: "false"
