# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/tasks.krun.io_ansibletasks.yaml
- bases/roles.krun.io_ansibleroles.yaml
- bases/blocks.krun.io_ansibleblocks.yaml
# +kubebuilder:scaffold:crdkustomizeresource
